##### Changes:

* Changed a bit of dask/dataframe/core.py near line 4111
* Changed a bit of dask_profiling/report.py near line 39

* Getting this error when `datetime` is in data but parking this error for now.

<details>
    ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-69826fa9d4bd> in <module>
----> 1 dask_profiling.ProfileReport(taxi_df_cdf)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask_profiling/__init__.py in __init__(self, df, **kwargs)
     65         sample = kwargs.get('sample', df.head())
     66 
---> 67         description_set = describe_df(df, **kwargs)
     68 
     69         self.html = to_html(sample,

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask_profiling/describe.py in describe(df, bins, check_correlation, correlation_threshold, correlation_overrides, check_recoded, pool_size, **kwargs)
    403         '''
    404         corr = dfcorrPear.copy()
--> 405         for x, corr_x in corr.iterrows():
    406             if correlation_overrides and x in correlation_overrides:
    407                 continue

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/core.py in iterrows(self)
   4111             print("This is the type",type(self))
   4112             for i in range(self.npartitions):
-> 4113                 df = self.get_partition(i).compute()
   4114                 df = df[0]
   4115                 for row in df.iterrows():

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    442         postcomputes.append(x.__dask_postcompute__())
    443 
--> 444     results = schedule(dsk, keys, **kwargs)
    445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    446 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    525     """
    526     kwargs.pop("num_workers", None)  # if num_workers present, remove it
--> 527     return get_async(apply_sync, 1, dsk, keys, **kwargs)
    528 
    529 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    469             # Seed initial tasks into the thread pool
    470             while state["ready"] and len(state["running"]) < num_workers:
--> 471                 fire_task()
    472 
    473             # Main loop, wait on tasks to finish, insert new ones

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in fire_task()
    464                         pack_exception,
    465                     ),
--> 466                     callback=queue.put,
    467                 )
    468 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in apply_sync(func, args, kwds, callback)
    514 def apply_sync(func, args=(), kwds={}, callback=None):
    515     """ A naive synchronous version of apply_async """
--> 516     res = func(*args, **kwds)
    517     if callback is not None:
    518         callback(res)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    225         failed = False
    226     except BaseException as e:
--> 227         result = pack_exception(e, dumps)
    228         failed = True
    229     return key, result, failed

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/core.py in cov_corr_chunk(df, corr)
   5523     """
   5524     shape = (df.shape[1], df.shape[1])
-> 5525     df = df.astype("float64", copy=False)
   5526     sums = zeros_like_safe(df.values, shape=shape)
   5527     counts = zeros_like_safe(df.values, shape=shape)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors, **kwargs)
   5880             # else, only a single dtype is given
   5881             new_data = self._data.astype(
-> 5882                 dtype=dtype, copy=copy, errors=errors, **kwargs
   5883             )
   5884             return self._constructor(new_data).__finalize__(self)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/internals/managers.py in astype(self, dtype, **kwargs)
    579 
    580     def astype(self, dtype, **kwargs):
--> 581         return self.apply("astype", dtype=dtype, **kwargs)
    582 
    583     def convert(self, **kwargs):

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/internals/managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
    436                     kwargs[k] = obj.reindex(b_items, axis=axis, copy=align_copy)
    437 
--> 438             applied = getattr(b, f)(**kwargs)
    439             result_blocks = _extend_blocks(applied, result_blocks)
    440 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors, values, **kwargs)
    557 
    558     def astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):
--> 559         return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
    560 
    561     def _astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/internals/blocks.py in _astype(self, dtype, **kwargs)
   2264 
   2265         # delegate
-> 2266         return super()._astype(dtype=dtype, **kwargs)
   2267 
   2268     def _can_hold_element(self, element):

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/internals/blocks.py in _astype(self, dtype, copy, errors, values, **kwargs)
    641                     # _astype_nansafe works fine with 1-d only
    642                     vals1d = values.ravel()
--> 643                     values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
    644 
    645                 # TODO(extension)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    668         raise TypeError(
    669             "cannot astype a datetimelike from [{from_dtype}] "
--> 670             "to [{to_dtype}]".format(from_dtype=arr.dtype, to_dtype=dtype)
    671         )
    672 

TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64]
    
    </details>

In [1]:
import dask
import dask.dataframe as dd
import pandas as pd
import numpy as np

In [2]:
import dask_profiling

In [3]:
import holoviews as hv
from holoviews import opts
import cupy
import dask_cudf
import cudf

In [4]:
from dask import compute

In [5]:
#dask.com

In [6]:
#from dask_cudf import compute

In [7]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,4,5,6,7"

In [8]:
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
client = Client(cluster)

# forces workers to restart. useful to ensure GPU memory is clear
client.restart()

distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker

In [9]:
#Dictionary of required columns and their datatypes
must_haves = {
     'pickup_datetime': 'datetime64[ns]',
     'dropoff_datetime': 'datetime64[ns]',
     'passenger_count': 'int32',
     'trip_distance': 'float32',
     'pickup_longitude': 'float32',
     'pickup_latitude': 'float32',
     'rate_code': 'int32',
     'dropoff_longitude': 'float32',
     'dropoff_latitude': 'float32',
     'fare_amount': 'float32'
    }

In [10]:
def clean(ddf, must_haves):
    # replace the extraneous spaces in column names and lower the font type
    tmp = {col:col.strip().lower() for col in list(ddf.columns)}
    ddf = ddf.rename(columns=tmp)

    ddf = ddf.rename(columns={
        'tpep_pickup_datetime': 'pickup_datetime',
        'tpep_dropoff_datetime': 'dropoff_datetime',
        'ratecodeid': 'rate_code'
    })
    
    ddf['pickup_datetime'] = ddf['pickup_datetime'].astype('datetime64[ms]')
    ddf['dropoff_datetime'] = ddf['dropoff_datetime'].astype('datetime64[ms]')
    
    # print(type(ddf['pickup_datetime']))
    # pandas.astype() doesn't take datetime64[ms] so had to try [ns] instead for dask dataframe cleaning.
    # ddf['pickup_datetime'] = ddf['pickup_datetime'].astype('datetime64[ns]')
    # ddf['dropoff_datetime'] = ddf['dropoff_datetime'].astype('datetime64[ns]')
    
    #ddf['pickup_datetime'] = pd.to_datetime(ddf['pickup_datetime'])
    #ddf['dropoff_datetime'] = pd.to_datetime(ddf['dropoff_datetime'])


    for col in ddf.columns:
        if col not in must_haves:
            ddf = ddf.drop(columns=col)
            continue
        # if column was read as a string, recast as float
        if ddf[col].dtype == 'object':
            ddf[col] = ddf[col].str.fillna('-1')
            ddf[col] = ddf[col].astype('float32')
        else:
            # downcast from 64bit to 32bit types
            # Tesla T4 are faster on 32bit ops
            if 'int' in str(ddf[col].dtype):
                ddf[col] = ddf[col].astype('int32')
            if 'float' in str(ddf[col].dtype):
                ddf[col] = ddf[col].astype('float32')
            ddf[col] = ddf[col].fillna(-1)
    
    return ddf

In [11]:
base_path = '/datasets/nyc-taxi/'
months = [str(x).rjust(2, '0') for x in range(1, 7)]
valid_files = [base_path+'2016/yellow_tripdata_2016-'+month+'.csv' for month in months]

In [12]:
#reading as dask_cudf
taxi_df_cdf = dask_cudf.read_csv(valid_files[0],encoding='UTF-8',npartitions=8).map_partitions(clean, must_haves, meta=must_haves)

In [13]:
#reading as cudf
#taxi_df_cdf = clean(cudf.read_csv(valid_files[5]),must_haves)

In [14]:
type(taxi_df_cdf)

dask_cudf.core.DataFrame

##### Finding 2:
* In clean function, the astype(datetime64[ms]) is working for dask_cudf dataframe but is not working for dask dataframe. I also tried astype for just a pandas series which works and logically in map_partition it basically divides it into various pandas dataframe individually. Unable to figure out the real cause.

* Figured out that it was because the `must_have` meta had datetime64[s] set up and that is not supported for pandas Series.

### <font color=blue>When dask_cudf is imported then dask.map_partitions is converting the dataframe to dask_cudf dataframe. Check if it's okay or needs a bug here.

In [15]:
#Pandas to dask -> map_partitions is converting it to dask_cudf when dask_cudf is imported
taxi_df_cdf = dd.from_pandas(pd.read_csv(valid_files[0],encoding='UTF-8'),npartitions=8).map_partitions(clean, must_haves, meta=must_haves)

In [16]:
type(taxi_df_cdf)

dask_cudf.core.DataFrame

In [7]:
#Pandas to dask
taxi_df_ddf = dd.from_pandas(pd.read_csv(valid_files[0],encoding='UTF-8'),npartitions=8)#.map_partitions(clean, must_haves, meta=must_haves)

In [8]:
type(taxi_df_ddf)

dask.dataframe.core.DataFrame

##### debuging the datetime conversion error

In [11]:
# df = pd.read_csv(valid_files[0],encoding='UTF-8')

# type(df["tpep_pickup_datetime"])

# df["tpep_pickup_datetime"] = df["tpep_pickup_datetime"].astype("datetime64[s]")

# df["tpep_dropoff_datetime"] = df["tpep_dropoff_datetime"].astype("datetime64[s]")

In [12]:
#type(taxi_df_ddf)

In [51]:
#The get partitions giving error
# tmp = taxi_df_cdf.get_partition(1).compute()


# tmp = tmp[0]

In [17]:
# tmp = taxi_df_cdf.map_partitions(clean,must_haves,meta=must_haves)

# type(taxi_df_cdf.get_partition(1).compute())

# "dask_cudf" in str(type(taxi_df_cdf))

In [15]:
taxi_df_cdf = taxi_df_cdf[['passenger_count',
       'trip_distance', 'pickup_longitude', 'pickup_latitude', 'rate_code',
       'dropoff_longitude', 'dropoff_latitude', 'fare_amount']]

In [16]:
taxi_df_cdf.columns

Index(['passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'rate_code', 'dropoff_longitude', 'dropoff_latitude',
       'fare_amount'],
      dtype='object')

In [9]:
taxi_df_ddf.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object')

In [10]:
taxi_df_ddf = taxi_df_ddf[['VendorID',
       'passenger_count', 'trip_distance']]

In [20]:
taxi_df_ddf = taxi_df_ddf[['passenger_count',
       'trip_distance', 'pickup_longitude', 'pickup_latitude', 'rate_code',
       'dropoff_longitude', 'dropoff_latitude', 'fare_amount']]

In [19]:
# tmp = taxi_df_cdf.get_partition(1).compute()

# isinstance(tmp,cudf.DataFrame)

# tmp.to_pandas()

In [20]:
taxi_df_cdf.columns

Index(['passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'rate_code', 'dropoff_longitude', 'dropoff_latitude',
       'fare_amount'],
      dtype='object')

##### Finding 1:
    * So, if I read the data from pandas to dask to map_partitions then it becomes dask_cudf dataframe. In that scenario, `type(df.get_partitions(1).compute())` gives tuple.
    * But if read the data frame as dask_cudf.read_csv() in that case, `type(df.get_partitions(1).compute())` gives cudf.core.Dataframe.
    * But in both the cases when the code reaches, dask.Dataframe.core.py line 4111 it is getting converted to tuple situation. So there is something happening in the dask_profiling code that I will have to understand.

In [23]:
#if data is read as dask_cudf.read_csv
type(taxi_df_cdf.get_partition(1).compute())

cudf.core.dataframe.DataFrame

In [29]:
#if data is read as pandas->dask -> map_partitions
type(taxi_df_cdf.get_partition(1).compute())

tuple

In [30]:
#if data is read as pandas->dask -> map_partitions
type(taxi_df_cdf.get_partition(1).compute()[0])

pandas.core.frame.DataFrame

In [19]:
isinstance(taxi_df_cdf, dd.DataFrame)

True

In [18]:
isinstance(taxi_df_cdf, dask_cudf.DataFrame)

True

In [21]:
type(taxi_df_cdf)

dask_cudf.core.DataFrame

#### Verifying type(df[col]) gives what. For dask_profiling.describe.py line 391

In [27]:
type(taxi_df_cdf["passenger_count"]),type(taxi_df_ddf["passenger_count"])

(dask_cudf.core.Series, dask.dataframe.core.Series)

#### Checking few differences between dask_cudf.Series vs dask.Series

In [28]:
dask_cudf_series = taxi_df_cdf["passenger_count"]

In [29]:
dask_series = taxi_df_ddf["passenger_count"]

In [35]:
dask_cudf_series.size, dask_series.size

(dd.Scalar<size-ag..., dtype=int64>, dd.Scalar<size-ag..., dtype=int64>)

In [36]:
dask_cudf_series.count(), dask_series.count()

(dd.Scalar<sum-agg..., dtype=int64>, dd.Scalar<series-..., dtype=int64>)

In [38]:
dask_cudf_series.memory_usage(),dask_series.memory_usage()

(Delayed('sum-9260bab3-3f7a-4ef5-9d4c-d9ccf384c40c'),
 Delayed('sum-8eab69f5-411b-4f6a-a38a-a36137309530'))

In [39]:
dask_cudf_series.mean(),dask_series.mean()

(dd.Scalar<truediv..., dtype=float64>, dd.Scalar<series-..., dtype=float64>)

In [41]:
dask_cudf_series.var(),dask_series.var()

(dd.Scalar<series-..., dtype=float64>, dd.Scalar<series-..., dtype=float64>)

In [42]:
dask_cudf_series.to_dask_array()#,dask_series.var()

dask.array<values, shape=(nan,), dtype=int32, chunksize=(nan,), chunktype=numpy.ndarray>

In [43]:
dask_series.to_dask_array()

dask.array<values, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>

In [65]:
dask_cudf_series.size

dd.Scalar<size-ag..., dtype=int64>

In [11]:
dask_profiling.ProfileReport(taxi_df_ddf)

This is the current col being described  VendorID
Getting var type worked
Understood type of this col data  BOOL
This is the current col being described  passenger_count
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  trip_distance
Getting var type worked
Understood type of this col data  NUM
This is the type for pearson correlation data <class 'dask_cudf.core.DataFrame'>
The type of data reached at iterrows  <class 'dask_cudf.core.DataFrame'>
The data type of the partition in iterrows  <class 'tuple'>

AttributeError: 'tuple' object has no attribute 'iterrows'

### Add an issue for the cudf.Series.size() not there.

In [19]:
tmp = taxi_df_cdf.get_partition(1).compute()

In [18]:
#tmp.iterrows()

### <font color=blue> Need to understand what's happening to the data as it goes into dask_profiling code. Why does the dask.dataframe.core.iterrows() part is breaking. Why does it return tuple or list whenever I run compute and also, why does the individual dataframe after compute gets converted to pandas.core.frame.Dataframe instead of cudf.core.frame.Dataframe? </font>

<font color=blue> The size parameter in cudf.core.Series is still missing in my remote version, even thought the update is been corrected on Git. Need to install the latest version </font>

<font color=blue> The value_counts in cudf.core.Series.value_counts() is also not updated to the new version which takes the parameter `ascending` even after installing the latest build. The latest git code has the correct function so copied it from Git for now.</font>

<font color=blue> Solved the problem of value_counts(), but now getting the error of `inferred_type` for the value_counts() output</font>

<font color=blue> Commented and moved on from the `inferred_type` issue. </font>

<font color=blue> Getting the issue of cupy.array in `scipy.stats.stats.py` 
    
Changed line 221 in `scipy.stats.stats.py` to incorporate for cupy array.
</font>

<font color=blue> For some reason, I am not getting the `scipy.stats.stats` error even after commenting the change that I made.
</font>


<font color=blue> Realized that current dataset has all values as num vartype. Testing various operations in `dask_profiling.describe.describe_numeric_1d()`.
    See more details below in the notebook.
</font>



<font color=blue> Most of the values reaching at `dask_profiling.report.fmt()` are numpy array but 1 value reaching there is cupy array and that's throwing an error at pd.isnull(). Parking here for today, will resume from here tomorrow.
</font>

<font color=blue> Solved that and got stuck at `dask_profiling.report.freq_table()`.  cudf.Series doesn't have a method called `items()` unlike, pandas.Series()
</font>

#### IMP points list

<font color=blue> Most of the values reaching at `dask_profiling.report.fmt()` are numpy array but 1 value reaching there is cupy array and that's throwing an error at pd.isnull(). Parking here for today, will resume from here tomorrow.
</font>

In [17]:
dask_profiling.ProfileReport(taxi_df_cdf)

This is the current col being described  index
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  passenger_count
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  trip_distance
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  pickup_longitude
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  pickup_latitude
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  rate_code
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  dropoff_longitude
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  dropoff_latitude
Getting var type worked
Understood type of this col data  NUM
This is the current col being described  fare_amount
Getting var type worked
Understood type of this col data  NUM
This is the type for pearson correlation data <class 'dask_cudf.core.DataFrame'>
The type of data reached at iterrows  <class 'dask_cudf.core.DataFrame'>
The data type of the partition in iterrows  <class 'list'>
Size of the list:  1
Type of 1st element  <class 'pandas.core.frame.DataFrame'>
This is the type of data at to_html <class 'dict'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>

The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  distinct_count  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_missing  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_missing  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  p_infinite  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_infinite  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  is_unique  is  <class 'numpy.bool_'>
Type of data in dask_profiling.report.fmt() for  mode  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_unique  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  memorysize  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  type  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  mean  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  std  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  variance  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  min  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  max  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  range  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  5%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  25%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  50%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  75%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  95%  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  iqr  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  skewness  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  sum  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  mad  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  cv  is  <class 'numpy.float64'>
Type of data in dask_profiling.report.fmt() for  n_zeros  is  <class 'numpy.ndarray'>
Type of data in dask_profiling.report.fmt() for  p_zeros  is  <class 'numpy.float64'>
The type of freqtable data at dask_profiling.report.freq_table is  <class 'pandas.core.series.Series'>
The type of freqtable data at dask_profiling.report.freq_table iloc is  <class 'pandas.core.series.Series'>
Type of data in dask_profiling.report.fmt() for  n  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  nvar  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  total_missing  is  <class 'float'>
Type of data in dask_profiling.report.fmt() for  n_duplicates  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  memsize  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  recordsize  is  <class 'str'>
Type of data in dask_profiling.report.fmt() for  NUM  is  <class 'numpy.int64'>
Type of data in dask_profiling.report.fmt() for  DATE  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  CONST  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  CAT  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  UNIQUE  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  CORR  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  RECODED  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  BOOL  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  UNSUPPORTED  is  <class 'int'>
Type of data in dask_profiling.report.fmt() for  REJECTED  is  <class 'int'>
Data type at plot.correlation_matrix <class 'pandas.core.frame.DataFrame'>

findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.

### Trying different elements to understand the best usage certain parts

##### Debugging `dask_profiling.base.get_groupby_statistic()` function

In [19]:
d_c_series = taxi_df_cdf["trip_distance"]

In [20]:
d_c_series.size

dd.Scalar<size-ag..., dtype=int64>

In [54]:
d_p_series = taxi_df_ddf["trip_distance"]

In [ ]:
d_c_series.value_counts()

In [55]:
type(d_c_series), type(d_p_series)

(dask_cudf.core.Series, dask.dataframe.core.Series)

In [39]:
d_c_series.value_counts()

In [62]:
#### For a dask_cudf.Series
print(d_c_series.value_counts())
value_counts_with_nan = d_c_series.value_counts()
value_counts_without_nan = d_c_series.dropna().value_counts()
print(d_c_series.value_counts().count())
print(type(value_counts_without_nan))

value_counts_with_nan.head()
value_counts_with_nan.index.head()

<dask_cudf.Series | 36 tasks | 1 npartitions>
dd.Scalar<sum-agg..., dtype=int64>
<class 'dask_cudf.core.Series'>

Float64Index([0.8999999761581421,  0.800000011920929,                1.0,
               1.100000023841858,  0.699999988079071],
             dtype='float32')

In [64]:
isinstance(value_counts_without_nan,dask_cudf.Series)

True

#### Solving the error "AttributeError: 'GenericIndex' object has no attribute 'inferred_type'" 

### cudf.core.index.GenericIndex is missing attribute "inferred_type" unlike pandas.core.indexes.numeric.Float64Index

In [57]:
d_c_series_val_cal = d_c_series.value_counts().index.head()

In [58]:
type(d_c_series_val_cal)

cudf.core.index.GenericIndex

In [59]:
d_p_series_val_cal = d_p_series.value_counts().index.head()

In [60]:
type(d_p_series_val_cal)

pandas.core.indexes.numeric.Float64Index

In [61]:
d_p_series_val_cal.inferred_type

'floating'

In [ ]:
d_c_series_val_cal

In [56]:
#### For a dask.Series
print(d_p_series.value_counts())
value_counts_with_nan = d_p_series.value_counts()
value_counts_without_nan = d_p_series.dropna().value_counts()
print(d_p_series.value_counts().count())
print(type(value_counts_without_nan))

value_counts_with_nan.head()
value_counts_with_nan.index.head()

Dask Series Structure:
npartitions=1
    int64
      ...
Name: trip_distance, dtype: int64
Dask Name: value-counts-agg, 25 tasks
dd.Scalar<series-..., dtype=int64>
<class 'dask.dataframe.core.Series'>

Float64Index([0.9, 0.8, 1.0, 1.1, 0.7], dtype='float64')

In [38]:
c_series = d_c_series.compute()
p_series = d_p_series.compute()

In [39]:
type(c_series), type(p_series)

(cudf.core.series.Series, pandas.core.series.Series)

In [1]:
c_series.size

NameError: name 'c_series' is not defined

In [46]:
c_series.value_counts()

0.90          252833
0.80          251036
1.00          249272
1.10          240194
0.70          238000
               ...
1403240.50         1
1653402.00         1
2441418.75         1
4667468.50         1
8000010.00         1
Name: trip_distance, Length: 4513, dtype: int32

In [47]:
p_series.value_counts()

0.90      252833
0.80      251036
1.00      249272
1.10      240194
0.70      238000
           ...
58.40          1
40.54          1
58.10          1
40.96          1
272.20         1
Name: trip_distance, Length: 4513, dtype: int64

In [41]:
dask_profiling.base.get_groupby_statistic(d_c_series)

AttributeError: 'GenericIndex' object has no attribute 'inferred_type'

#### Realized that current dataset has all values as num vartype. Testing various operations in  `dask_profiling.describe.describe_numeric_1d()`

In [43]:
from dask import delayed, compute
import scipy as sp
from dask.array import stats as dask_stats

In [24]:
d_c_series.mean().compute()

4.648197010541441

In [25]:
d_c_series.std().compute()

2981.095272054915

In [26]:
d_c_series.var().compute()

8886929.021068167

In [27]:
d_c_series.min().compute()

0.0

In [28]:
d_c_series.max().compute()

8000010.0

In [29]:
(d_c_series.max() - d_c_series.min()).compute()

8000010.0

In [30]:
_series_no_na = d_c_series.dropna()

In [32]:
_series_no_na.quantile(0.25).compute()

array(1.01999998)

###### computing kurtosis is giving error right now. Commenting this.

In [42]:
#compute(delayed(sp.stats.kurtosis)(d_c_series))

In [45]:
compute(delayed(float)(dask_stats.skew(d_c_series.to_dask_array())))

(2200.3359375,)

In [46]:
compute(d_c_series.sum())

(50697224.75,)

In [48]:
#mad
compute(d_c_series.sub(d_c_series.mean()).abs().mean())

(5.0487471735673095,)

In [49]:
#CV
compute(d_c_series.std() / d_c_series.mean())

(641.3444321086693,)

In [52]:
#n_zeros
compute(d_c_series.size - delayed(cupy.count_nonzero)(d_c_series))

(array(64065),)

In [21]:
## Pandas APIs are working well with cudf.Series as well so currently letting it run with this itself.
## Will have to change that to cudf apis later in the code
pd.api.types.is_numeric_dtype(taxi_df_cdf["trip_distance"])

True

In [17]:
c_series = cudf.Series(taxi_df_cdf["passenger_count"].compute())

In [20]:
type(c_series)

cudf.core.series.Series

In [22]:
isinstance(c_series,cudf.Series)

True

In [18]:
isinstance(c_series,cudf.DataFrame)

False

In [ ]:
#taxi_df_cdf.get_partition(1).compute()[0]

In [23]:
type(taxi_df_cdf.get_partition(1).compute())

cudf.core.dataframe.DataFrame

In [25]:
#taxi_df_cdf[0]

In [9]:
help(dask_profiling)

Help on package dask_profiling:

NAME
    dask_profiling - Main module of dask-profiling.

DESCRIPTION
    Docstring is compliant with NumPy/SciPy documentation standard:
    https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
    See also for a short description of docstring:
    https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

PACKAGE CONTENTS
    base
    describe
    formatters
    plot
    report
    templates
    tests

CLASSES
    builtins.object
        ProfileReport

    class ProfileReport(builtins.object)
     |  ProfileReport(df, **kwargs)
     |
     |  Generate a profile report from a Dataset stored as a dask `DataFrame`.
     |
     |  Used has is it will output its content as an HTML report in a Jupyter notebook.
     |
     |  Attributes
     |  ----------
     |  df : DataFrame
     |      Data to be analyzed
     |  bins : int
     |      Number of bins in histogram.
     |      The default is 10.
     |  check_correlation : boolean
     |      Whether or not to check correlation.
     |      It's `True` by default.
     |  correlation_threshold: float
     |      Threshold to determine if the variable pair is correlated.
     |      The default is 0.9.
     |  correlation_overrides : list
     |      Variable names not to be rejected because they are correlated.
     |      There is no variable in the list (`None`) by default.
     |  check_recoded : boolean
     |      Whether or not to check recoded correlation (memory heavy feature).
     |      Since it's an expensive computation it can be activated for small datasets.
     |      `check_correlation` must be true to disable this check.
     |      It's `False` by default.
     |  pool_size : int
     |      Number of workers in thread pool
     |      The default is equal to the number of CPU.
     |
     |  Methods
     |  -------
     |  get_description
     |      Return the description (a raw statistical summary) of the dataset.
     |  get_rejected_variables
     |      Return the list of rejected variable or an empty list if there is no rejected variables.
     |  to_file
     |      Write the report to a file.
     |  to_html
     |      Return the report as an HTML string.
     |
     |  Methods defined here:
     |
     |  __init__(self, df, **kwargs)
     |      Constructor see class documentation
     |
     |  __str__(self)
     |      Overwrite of the str method.
     |
     |      Returns
     |      -------
     |      str
     |          A string representation of the object.
     |
     |  get_description(self)
     |      Return the description (a raw statistical summary) of the dataset.
     |
     |      Returns
     |      -------
     |      dict
     |          Containing the following keys:
     |              * table: general statistics on the dataset
     |              * variables: summary statistics for each variable
     |              * freq: frequency table
     |
     |  get_rejected_variables(self, threshold=0.9)
     |      Return a list of variable names being rejected for high
     |      correlation with one of remaining variables.
     |
     |      Parameters:
     |      ----------
     |      threshold : float
     |          Correlation value which is above the threshold are rejected
     |
     |      Returns
     |      -------
     |      list
     |          The list of rejected variables or an empty list if the correlation has not been computed.
     |
     |  to_file(self, outputfile='dask_profiling.default_outputfile')
     |      Write the report to a file.
     |
     |      By default a name is generated.
     |
     |      Parameters:
     |      ----------
     |      outputfile : str
     |          The name or the path of the file to generale including the extension (.html).
     |
     |  to_html(self)
     |      Generate and return complete template as lengthy string
     |          for using with frameworks.
     |
     |      Returns
     |      -------
     |      str
     |          The HTML output.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  file = None
     |
     |  html = ''

DATA
    DEFAULT_OUTPUTFILE = 'dask_profiling.default_outputfile'
    NO_OUTPUTFILE = 'dask_profiling.no_outputfile'

FILE
    /home/nfs/rabhojwani/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask_profiling/__init__.py

In [12]:
tmp = taxi_df_cdf.get_partition(1).compute()